apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-ui.fullname" . }}-config
  labels:
    {{- include "library-ui.labels" . | nindent 4 }}
  namespace: {{ include "library-ui.namespace" . }}
data:
  HTTP_PORT: "{{ .Values.configData.libraryUI.http.port }}"

